"""Shared state enums for both setup types — see docs/engine.md#setup-types."""
from __future__ import annotations

from enum import Enum


class BreakoutState(str, Enum):
    WATCH = "WATCH"
    APPROACHING = "APPROACHING"
    BREAKOUT_ATTEMPT = "BREAKOUT_ATTEMPT"
    CANDLE_CONFIRMATION = "CANDLE_CONFIRMATION"
    VOLUME_CONFIRMATION = "VOLUME_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    RETEST_PENDING = "RETEST_PENDING"
    RETEST_CONFIRMED = "RETEST_CONFIRMED"
    TRADE_ACTIVE = "TRADE_ACTIVE"
    TARGET_HIT = "TARGET_HIT"
    INVALIDATED = "INVALIDATED"
    SESSION_END = "SESSION_END"
    NOT_CONFIRMED = "NOT_CONFIRMED"  # hard-rejection sink, distinct from INVALIDATED (never reached CONFIRMED)


class DipBuyState(str, Enum):
    UPTREND_CONFIRMED = "UPTREND_CONFIRMED"
    PULLBACK_IN_PROGRESS = "PULLBACK_IN_PROGRESS"
    SUPPORT_TEST = "SUPPORT_TEST"
    REVERSAL_CANDLE = "REVERSAL_CANDLE"
    VOLUME_CONFIRMATION = "VOLUME_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    RETEST_PENDING = "RETEST_PENDING"
    RETEST_CONFIRMED = "RETEST_CONFIRMED"
    TRADE_ACTIVE = "TRADE_ACTIVE"
    TARGET_HIT = "TARGET_HIT"
    INVALIDATED = "INVALIDATED"
    SESSION_END = "SESSION_END"
    NOT_CONFIRMED = "NOT_CONFIRMED"


TERMINAL_STATES = {"TARGET_HIT", "INVALIDATED", "SESSION_END", "NOT_CONFIRMED"}


def is_terminal(state: str) -> bool:
    return state in TERMINAL_STATES
