"""add news_articles table

Revision ID: 215d847dfa14
Revises: 3a2d9f6358a6
Create Date: 2026-08-17 04:29:36.564856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215d847dfa14'
down_revision: Union[str, Sequence[str], None] = '3a2d9f6358a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_articles_severity', 'news_articles', ['severity'], unique=False)
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_index('ix_news_articles_symbol_published', 'news_articles', ['symbol', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_articles_symbol_published', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_index('ix_news_articles_severity', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
