"""initial v1 schema

Revision ID: 3a2d9f6358a6
Revises: 
Create Date: 2026-08-16 04:01:55.215567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2d9f6358a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_version', sa.String(length=64), nullable=False),
    sa.Column('setup_type', sa.String(length=16), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_mfe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('avg_mae', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('avg_holding_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('breakdown_by_score_bucket', sa.Text(), nullable=True),
    sa.Column('breakdown_by_sector', sa.Text(), nullable=True),
    sa.Column('breakdown_by_day_of_week', sa.Text(), nullable=True),
    sa.Column('breakdown_by_regime', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_results_version', 'backtest_results', ['strategy_version'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('listing_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('breakout_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('setup_type', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'setup_type', name='uq_candidate_stock_setup')
    )
    op.create_index('ix_candidates_state', 'breakout_candidates', ['state'], unique=False)
    op.create_table('breakout_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('setup_type', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('transition_event', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_stock_setup_date', 'breakout_events', ['stock_id', 'setup_type', 'trade_date'], unique=False)
    op.create_table('daily_ohlcv',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_daily_ohlcv_stock_date')
    )
    op.create_index('ix_daily_ohlcv_stock_date', 'daily_ohlcv', ['stock_id', 'trade_date'], unique=False)
    op.create_table('support_resistance_levels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('level_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('strength', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_srlevels_stock_date', 'support_resistance_levels', ['stock_id', 'trade_date'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ema9', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema20', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sma100', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sma200', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('atr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_indicators_stock_date')
    )
    op.create_index('ix_indicators_stock_date', 'technical_indicators', ['stock_id', 'trade_date'], unique=False)
    op.create_table('trade_setups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('setup_type', sa.String(length=16), nullable=False),
    sa.Column('strategy_version', sa.String(length=64), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('target_1r', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('target_1_5r', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('target_2r', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('target_3r', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('nearest_structural_target', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_setups_setup_type', 'trade_setups', ['setup_type'], unique=False)
    op.create_index('ix_setups_stock_version', 'trade_setups', ['stock_id', 'strategy_version'], unique=False)
    op.create_table('trade_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_setup_id', sa.BigInteger(), nullable=False),
    sa.Column('mfe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mae', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target_hit', sa.String(length=16), nullable=True),
    sa.Column('sl_hit', sa.Boolean(), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trade_setup_id'], ['trade_setups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_setup_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_outcomes')
    op.drop_index('ix_setups_stock_version', table_name='trade_setups')
    op.drop_index('ix_setups_setup_type', table_name='trade_setups')
    op.drop_table('trade_setups')
    op.drop_index('ix_indicators_stock_date', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('ix_srlevels_stock_date', table_name='support_resistance_levels')
    op.drop_table('support_resistance_levels')
    op.drop_index('ix_daily_ohlcv_stock_date', table_name='daily_ohlcv')
    op.drop_table('daily_ohlcv')
    op.drop_index('ix_events_stock_setup_date', table_name='breakout_events')
    op.drop_table('breakout_events')
    op.drop_index('ix_candidates_state', table_name='breakout_candidates')
    op.drop_table('breakout_candidates')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('ix_backtest_results_version', table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
